/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import controlMySQL.MySqlConn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ernesto CH
 */
public class DisponibilidadPisos extends javax.swing.JPanel {
    MySqlConn conn = new MySqlConn();
    /**
     * Creates new form DisponibilidadPisos
     */
    public DisponibilidadPisos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonPiso1 = new javax.swing.JButton();
        jButtonPiso2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Consultar Disponibilidad Piso 1 o Piso 2");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonPiso1.setText("Piso 1");
        jButtonPiso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiso1ActionPerformed(evt);
            }
        });

        jButtonPiso2.setText("Piso 2");
        jButtonPiso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiso2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButtonPiso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPiso2)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPiso1)
                    .addComponent(jButtonPiso2))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPiso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiso1ActionPerformed
       this.jTextArea1.setText("");
       this.jTextArea1.append("En el piso 1 estan disponibles las habitaciones: \n\n");
       String query = "Select * From habitaciones";
       Statement st;
       ResultSet resultados;
       String tipohab,hab,salida,ocupado;
       try {
            st = this.conn.conn.createStatement();
            resultados = st.executeQuery(query);
            for (int i = 0; i < 15; i++) {
                resultados.next();
                        hab = resultados.getString("num_habitacion");
                        tipohab = resultados.getString("tipo_habitacion");
                        ocupado = resultados.getString("Ocupado");
                             if(ocupado.equals("1")){
                                 
                        }else{
                                salida = "Habitacion: " + hab + "\n"
                                + "Tipo de Habitacion: " + tipohab+ "\n\n";
                                 this.jTextArea1.append(salida);
                        }
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos");
        }
    }//GEN-LAST:event_jButtonPiso1ActionPerformed

    private void jButtonPiso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiso2ActionPerformed
        this.jTextArea1.setText("");
        this.jTextArea1.append("En el piso 2 estan disponibles las habitaciones: \n\n");
        String query = "Select * From habitaciones";
       Statement st;
       ResultSet resultados = null;
       String tipohab,hab,salida,ocupado;
        try {
            st = this.conn.conn.createStatement();
            resultados = st.executeQuery(query);
        } catch (SQLException ex) {
            Logger.getLogger(DisponibilidadPisos.class.getName()).log(Level.SEVERE, null, ex);
        }
       try {
            for (int i = 15; i < 30; i++) {
                resultados.absolute(i);
                resultados.next();
                        hab = resultados.getString("num_habitacion");
                        tipohab = resultados.getString("tipo_habitacion");
                        ocupado = resultados.getString("Ocupado");
                             if(ocupado.equals("1")){
                                 
                        }else{
                                salida = "Habitacion: " + hab + "\n"
                                + "Tipo de Habitacion: " + tipohab+ "\n\n";
                                 this.jTextArea1.append(salida);
                        }
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos");
        }
    }//GEN-LAST:event_jButtonPiso2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPiso1;
    private javax.swing.JButton jButtonPiso2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
