/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import controlMySQL.MySqlConn;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ernesto CH
 */
public class Grafica extends javax.swing.JPanel {
    MySqlConn conn = new MySqlConn();
    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMostrarGrafica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButtonMostrarGrafica.setText("Mostrar Grafica");
        jButtonMostrarGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarGraficaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Consultar Ocupacion por tipo de habitacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButtonMostrarGrafica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(jButtonMostrarGrafica)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    boolean band = false;
    
    private void jButtonMostrarGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarGraficaActionPerformed
        band = true;
        repaint();
    }//GEN-LAST:event_jButtonMostrarGraficaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMostrarGrafica;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void paint(Graphics g){
     super.paint(g);
     if(band == true){
            String ocupado,tipo;
            int sencilla = 0,doble =0,triple = 0;
            try {
                String query = "Select * From habitaciones";
                Statement st;
                ResultSet resultados ;
                st = this.conn.conn.createStatement();
                resultados = st.executeQuery(query);
                while(resultados.next()){
                    ocupado = resultados.getString("Ocupado");
                    tipo    = resultados.getString("tipo_habitacion");
                    if(ocupado.equals("1") && tipo.equals("Sencilla")){
                        sencilla++;
                    }else if(ocupado.equals("1") && tipo.equals("Doble")){
                        doble++;
                    }else if(ocupado.equals("1") && tipo.equals("Triple")){
                        triple++;
                    }
                }
                
                float total = sencilla+doble+triple;
                
                float se = sencilla*100/total;
                float dob = doble *100/total;
                float tr = triple*100/total;
                
                float gradosen = sencilla*360/total;
                float gradosdo = doble*360/total;
                float gradostri = triple*360/total;
                
                int en,dobl,tri,senc,dobles,tripl;
                en = Math.round(gradosen);
                dobl = Math.round(gradosdo);
                tri = Math.round(gradostri);
                
                senc = Math.round(se);
                dobles = Math.round(dob);
                tripl = Math.round(tr);
                
                String s,d,t;
                s = String.valueOf(senc);
                d = String.valueOf(dobles);
                t = String.valueOf(tripl);
                
                g.setColor(Color.DARK_GRAY);
                g.fillArc(25,80,200,200,0,en);
                g.fillRect(250, 120,20,20);
                g.drawString("Sencilla",275,135);
                g.drawString(s + " %", 340, 135);
                
                g.setColor(Color.orange);
                g.fillArc(25,80,200,200,en,dobl);
                g.fillRect(250,150,20,20);
                g.drawString("Doble",275,165);
                g.drawString(d + " %", 340, 165);
                
                g.setColor(Color.LIGHT_GRAY);
                g.fillArc(25,80,200,200,dobl+en,tri);
                g.fillRect(250,180,20,20);
                g.drawString("Triple",275,195);
                g.drawString(t + " %", 340, 195);
                
            } catch (SQLException ex) {
                Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
