/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import controlMySQL.MySqlConn;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ernesto CH
 */
public class TotalHabitaciones extends javax.swing.JPanel {
    MySqlConn conn = new MySqlConn();
    /**
     * Creates new form TotalHabitaciones
     */
    public TotalHabitaciones() {
        initComponents();
    }
    
    boolean band = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonMostrarGraficas = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Grafica total de habitaciones");

        jButtonMostrarGraficas.setText("Mostrar Grafica");
        jButtonMostrarGraficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarGraficasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonMostrarGraficas)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(jButtonMostrarGraficas)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarGraficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarGraficasActionPerformed
        band = true;
        repaint();
    }//GEN-LAST:event_jButtonMostrarGraficasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMostrarGraficas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    public int mayor(int sencilla,int doble,int triple){
        if(sencilla > doble && sencilla > triple){
            return sencilla;
        }else if(doble > triple){
            return doble;
        }else{
            return triple;
        }
    }
    
    public void paint(Graphics g){
        super.paint(g);
        String tipo;
        int  sencilla = 0,doble=0,triple=0;
        if(band == true){
            try {
                String query = "Select * From habitaciones";
                Statement st;
                ResultSet resultados ;
                st = this.conn.conn.createStatement();
                resultados = st.executeQuery(query);
                
                while(resultados.next()){
                   tipo = resultados.getString("tipo_habitacion");
                   switch(tipo){
                       case "Sencilla":
                           sencilla++;
                           break;
                       case "Doble":
                           doble++;
                           break;
                       case "Triple":
                           triple++;
                           break;
                   }
                }
                
                int mayor = mayor(sencilla,doble,triple);
                
                int largos = sencilla*400/mayor;
                int largod = doble*400/mayor;
                int largot = triple*400/mayor;
                
                String s = String.valueOf(sencilla);
                String d = String.valueOf(doble);
                String t = String.valueOf(triple);
                
                
                g.setColor(Color.BLUE);
                g.fillRect(100, 100, largos, 40);
                g.drawString("Sencilla", 10, 125);
                g.setColor(Color.BLACK);
                g.drawString(s, 70,125);
                
                g.setColor(Color.DARK_GRAY);
                g.fillRect(100, 150, largod, 40);
                g.drawString("Doble", 10, 175);
                g.setColor(Color.BLACK);
                g.drawString(d, 70,175);
                
                g.setColor(Color.GREEN);
                g.fillRect(100, 200, largot, 40);
                g.drawString("Triple", 10, 215);
                g.setColor(Color.BLACK);
                g.drawString(t, 70,215);
                
            } catch (SQLException ex) {
                Logger.getLogger(TotalHabitaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
