/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

/**
 *
 * @author Ernesto CH
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBienvenida = new javax.swing.JPanel();
        jPanelGaleria = new javax.swing.JPanel();
        JPanelIngresos = new javax.swing.JPanel();
        jPanelOcupación = new javax.swing.JPanel();
        JPanelCostos = new javax.swing.JPanel();
        jPanelHuesped = new javax.swing.JPanel();
        jPanelHabitación = new javax.swing.JPanel();
        jPanelPisos = new javax.swing.JPanel();
        jPanelListaHuesped = new javax.swing.JPanel();
        jPanelFechayHoraActual = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelBienvenidaLayout = new javax.swing.GroupLayout(jPanelBienvenida);
        jPanelBienvenida.setLayout(jPanelBienvenidaLayout);
        jPanelBienvenidaLayout.setHorizontalGroup(
            jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanelBienvenidaLayout.setVerticalGroup(
            jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Menu Consultas", jPanelBienvenida);

        javax.swing.GroupLayout jPanelGaleriaLayout = new javax.swing.GroupLayout(jPanelGaleria);
        jPanelGaleria.setLayout(jPanelGaleriaLayout);
        jPanelGaleriaLayout.setHorizontalGroup(
            jPanelGaleriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanelGaleriaLayout.setVerticalGroup(
            jPanelGaleriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Galeria", jPanelGaleria);

        javax.swing.GroupLayout JPanelIngresosLayout = new javax.swing.GroupLayout(JPanelIngresos);
        JPanelIngresos.setLayout(JPanelIngresosLayout);
        JPanelIngresosLayout.setHorizontalGroup(
            JPanelIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        JPanelIngresosLayout.setVerticalGroup(
            JPanelIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ingresos", JPanelIngresos);

        javax.swing.GroupLayout jPanelOcupaciónLayout = new javax.swing.GroupLayout(jPanelOcupación);
        jPanelOcupación.setLayout(jPanelOcupaciónLayout);
        jPanelOcupaciónLayout.setHorizontalGroup(
            jPanelOcupaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanelOcupaciónLayout.setVerticalGroup(
            jPanelOcupaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ocupación", jPanelOcupación);

        javax.swing.GroupLayout JPanelCostosLayout = new javax.swing.GroupLayout(JPanelCostos);
        JPanelCostos.setLayout(JPanelCostosLayout);
        JPanelCostosLayout.setHorizontalGroup(
            JPanelCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        JPanelCostosLayout.setVerticalGroup(
            JPanelCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Costos", JPanelCostos);

        javax.swing.GroupLayout jPanelHuespedLayout = new javax.swing.GroupLayout(jPanelHuesped);
        jPanelHuesped.setLayout(jPanelHuespedLayout);
        jPanelHuespedLayout.setHorizontalGroup(
            jPanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanelHuespedLayout.setVerticalGroup(
            jPanelHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Buscar Huesped", jPanelHuesped);

        javax.swing.GroupLayout jPanelHabitaciónLayout = new javax.swing.GroupLayout(jPanelHabitación);
        jPanelHabitación.setLayout(jPanelHabitaciónLayout);
        jPanelHabitaciónLayout.setHorizontalGroup(
            jPanelHabitaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanelHabitaciónLayout.setVerticalGroup(
            jPanelHabitaciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Buscar Habitación", jPanelHabitación);

        javax.swing.GroupLayout jPanelPisosLayout = new javax.swing.GroupLayout(jPanelPisos);
        jPanelPisos.setLayout(jPanelPisosLayout);
        jPanelPisosLayout.setHorizontalGroup(
            jPanelPisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanelPisosLayout.setVerticalGroup(
            jPanelPisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pisos", jPanelPisos);

        javax.swing.GroupLayout jPanelListaHuespedLayout = new javax.swing.GroupLayout(jPanelListaHuesped);
        jPanelListaHuesped.setLayout(jPanelListaHuespedLayout);
        jPanelListaHuespedLayout.setHorizontalGroup(
            jPanelListaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanelListaHuespedLayout.setVerticalGroup(
            jPanelListaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista Huespedes", jPanelListaHuesped);

        javax.swing.GroupLayout jPanelFechayHoraActualLayout = new javax.swing.GroupLayout(jPanelFechayHoraActual);
        jPanelFechayHoraActual.setLayout(jPanelFechayHoraActualLayout);
        jPanelFechayHoraActualLayout.setHorizontalGroup(
            jPanelFechayHoraActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jPanelFechayHoraActualLayout.setVerticalGroup(
            jPanelFechayHoraActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fecha y Hora", jPanelFechayHoraActual);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelCostos;
    private javax.swing.JPanel JPanelIngresos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBienvenida;
    private javax.swing.JPanel jPanelFechayHoraActual;
    private javax.swing.JPanel jPanelGaleria;
    private javax.swing.JPanel jPanelHabitación;
    private javax.swing.JPanel jPanelHuesped;
    private javax.swing.JPanel jPanelListaHuesped;
    private javax.swing.JPanel jPanelOcupación;
    private javax.swing.JPanel jPanelPisos;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
