/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ernesto CH
 */
public class ConsultasSubMenu extends javax.swing.JPanel {

    /**
     * Creates new form ConsultasSubMenu
     */
    public ConsultasSubMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelGaleria = new javax.swing.JPanel();
        jPanelIngresos = new javax.swing.JPanel();
        jPanelDisponibilidad = new javax.swing.JPanel();
        jPanelCostos = new javax.swing.JPanel();
        jPanelBuscarHuesped = new javax.swing.JPanel();
        jPanelBuscarHabitacion = new javax.swing.JPanel();
        jPanelPisos = new javax.swing.JPanel();
        jPanelListaHuesped = new javax.swing.JPanel();
        listaHuespedes1 = new consultas.ListaHuespedes();
        jPanelFechayHora = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanelGaleriaLayout = new javax.swing.GroupLayout(jPanelGaleria);
        jPanelGaleria.setLayout(jPanelGaleriaLayout);
        jPanelGaleriaLayout.setHorizontalGroup(
            jPanelGaleriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanelGaleriaLayout.setVerticalGroup(
            jPanelGaleriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Galeria", jPanelGaleria);

        javax.swing.GroupLayout jPanelIngresosLayout = new javax.swing.GroupLayout(jPanelIngresos);
        jPanelIngresos.setLayout(jPanelIngresosLayout);
        jPanelIngresosLayout.setHorizontalGroup(
            jPanelIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanelIngresosLayout.setVerticalGroup(
            jPanelIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ingresos", jPanelIngresos);

        javax.swing.GroupLayout jPanelDisponibilidadLayout = new javax.swing.GroupLayout(jPanelDisponibilidad);
        jPanelDisponibilidad.setLayout(jPanelDisponibilidadLayout);
        jPanelDisponibilidadLayout.setHorizontalGroup(
            jPanelDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanelDisponibilidadLayout.setVerticalGroup(
            jPanelDisponibilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Disponibilidad", jPanelDisponibilidad);

        javax.swing.GroupLayout jPanelCostosLayout = new javax.swing.GroupLayout(jPanelCostos);
        jPanelCostos.setLayout(jPanelCostosLayout);
        jPanelCostosLayout.setHorizontalGroup(
            jPanelCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanelCostosLayout.setVerticalGroup(
            jPanelCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Costos", jPanelCostos);

        javax.swing.GroupLayout jPanelBuscarHuespedLayout = new javax.swing.GroupLayout(jPanelBuscarHuesped);
        jPanelBuscarHuesped.setLayout(jPanelBuscarHuespedLayout);
        jPanelBuscarHuespedLayout.setHorizontalGroup(
            jPanelBuscarHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanelBuscarHuespedLayout.setVerticalGroup(
            jPanelBuscarHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Buscar Huesped", jPanelBuscarHuesped);

        javax.swing.GroupLayout jPanelBuscarHabitacionLayout = new javax.swing.GroupLayout(jPanelBuscarHabitacion);
        jPanelBuscarHabitacion.setLayout(jPanelBuscarHabitacionLayout);
        jPanelBuscarHabitacionLayout.setHorizontalGroup(
            jPanelBuscarHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanelBuscarHabitacionLayout.setVerticalGroup(
            jPanelBuscarHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Buscar Habitación", jPanelBuscarHabitacion);

        javax.swing.GroupLayout jPanelPisosLayout = new javax.swing.GroupLayout(jPanelPisos);
        jPanelPisos.setLayout(jPanelPisosLayout);
        jPanelPisosLayout.setHorizontalGroup(
            jPanelPisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanelPisosLayout.setVerticalGroup(
            jPanelPisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pisos", jPanelPisos);

        javax.swing.GroupLayout jPanelListaHuespedLayout = new javax.swing.GroupLayout(jPanelListaHuesped);
        jPanelListaHuesped.setLayout(jPanelListaHuespedLayout);
        jPanelListaHuespedLayout.setHorizontalGroup(
            jPanelListaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaHuespedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaHuespedes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelListaHuespedLayout.setVerticalGroup(
            jPanelListaHuespedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaHuespedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listaHuespedes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de Huespedes", jPanelListaHuesped);

        jPanelFechayHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFechayHoraMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelFechayHoraLayout = new javax.swing.GroupLayout(jPanelFechayHora);
        jPanelFechayHora.setLayout(jPanelFechayHoraLayout);
        jPanelFechayHoraLayout.setHorizontalGroup(
            jPanelFechayHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanelFechayHoraLayout.setVerticalGroup(
            jPanelFechayHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fecha y Hora", jPanelFechayHora);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelFechayHoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFechayHoraMouseEntered
        int op = JOptionPane.showConfirmDialog(this.jPanelFechayHora,"Desea consultar la fecha y hora del sistema?....");
        if(op == 0){
            java.util.Date fecha = new Date();
            String dia = String.valueOf(fecha);
            JOptionPane.showMessageDialog(jPanelFechayHora,dia,"Fecha y Hora Actual del Sistema",1);
            System.out.println("Selecciono si");
            System.out.println("Si ven esto ya chingue");
        }else if(op == 1){
            System.out.println("Selecciono no");
        }else{
            System.out.println("Secelcciono cancelar");
        }
    }//GEN-LAST:event_jPanelFechayHoraMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelBuscarHabitacion;
    private javax.swing.JPanel jPanelBuscarHuesped;
    private javax.swing.JPanel jPanelCostos;
    private javax.swing.JPanel jPanelDisponibilidad;
    private javax.swing.JPanel jPanelFechayHora;
    private javax.swing.JPanel jPanelGaleria;
    private javax.swing.JPanel jPanelIngresos;
    private javax.swing.JPanel jPanelListaHuesped;
    private javax.swing.JPanel jPanelPisos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private consultas.ListaHuespedes listaHuespedes1;
    // End of variables declaration//GEN-END:variables
}
