/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;
import controlMySQL.MySqlConn;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author roy_z
 */
public class registro extends javax.swing.JPanel {
     MySqlConn conn;
    /**
     * Creates new form registro
     */
       public registro (MySqlConn conn) {
        this.conn = conn;
        initComponents();
    }
    public registro() {
        initComponents();
    }
     /*  public frmJcalendar() {
        initComponents();                                                   ESTO ES PARA IMPRIMIR LAS FECHAS 
        this.tabladefechas.setModel(modelo);                                NOS SIRVE PARA LA SALIDA EN LA CREACION DEL TICKET
        this.modelo.addColumn("Fecha");
        
    }*/


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelFechaLlegada = new javax.swing.JLabel();
        jLabelNumeroPersonas = new javax.swing.JLabel();
        jLabelFechaSalida = new javax.swing.JLabel();
        jLabelHabitacionTipo = new javax.swing.JLabel();
        jLabelNumeroPiso = new javax.swing.JLabel();
        jLabelLimiteHuesped = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldLimiteHuesped = new javax.swing.JTextField();
        jDateChooserFechaLlegada = new com.toedter.calendar.JDateChooser();
        jDateChooserFechaSalida = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBoxHabitacionTipo = new javax.swing.JComboBox<>();
        jSpinnerNumeroPersona = new javax.swing.JSpinner();
        jSpinnerNumeroPiso = new javax.swing.JSpinner();
        jCheckBox1Personaextra = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jLabelHabitacionNumero = new javax.swing.JLabel();
        jTextFieldHabitacionNumero = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNombre.setText("NOMBRE DEL HUESPED");

        jLabelTitulo.setFont(new java.awt.Font("MS UI Gothic", 1, 26)); // NOI18N
        jLabelTitulo.setText("R E G I S T R O ");

        jLabelCiudad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCiudad.setText("CIUDAD DE ORIGEN");

        jLabelFechaLlegada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFechaLlegada.setText("FECHA DE LLEGADA");

        jLabelNumeroPersonas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNumeroPersonas.setText("NUMERO DE PERSONAS");

        jLabelFechaSalida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFechaSalida.setText("FECHA DE SALIDA");

        jLabelHabitacionTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHabitacionTipo.setText("TIPO DE HABITACION");

        jLabelNumeroPiso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNumeroPiso.setText("NUMERO DE PISO");

        jLabelLimiteHuesped.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLimiteHuesped.setText("LIMITE HUESPED");

        jTextFieldNombre.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldCiudad.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jTextFieldCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiudadActionPerformed(evt);
            }
        });

        jTextFieldLimiteHuesped.setEditable(false);
        jTextFieldLimiteHuesped.setFont(new java.awt.Font("MS UI Gothic", 0, 11)); // NOI18N
        jTextFieldLimiteHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLimiteHuespedActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBoxHabitacionTipo.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jComboBoxHabitacionTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Doble", "Triple" }));

        jSpinnerNumeroPersona.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jSpinnerNumeroPersona.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jSpinnerNumeroPersonaAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jSpinnerNumeroPiso.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N

        jCheckBox1Personaextra.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jCheckBox1Personaextra.setText("1 PERSONA EXTRA");
        jCheckBox1Personaextra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1PersonaextraActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jCheckBox2.setText("2 PERSONAS EXTRA");

        jButtonRegistrar.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButtonRegistrar.setText("REGISTRAR");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButtonLimpiar.setText("LIMPIAR");

        jButtonMostrar.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButtonMostrar.setText("MOSTRAR");

        jLabelHabitacionNumero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHabitacionNumero.setText("NUMERO DE HABITACION");

        jTextFieldHabitacionNumero.setFont(new java.awt.Font("MS UI Gothic", 0, 11)); // NOI18N
        jTextFieldHabitacionNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHabitacionNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitulo)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumeroPersonas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHabitacionTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHabitacionNumero, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelFechaSalida)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelFechaLlegada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateChooserFechaLlegada, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                        .addComponent(jDateChooserFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCiudad)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHabitacionNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSpinnerNumeroPersona)
                                            .addComponent(jComboBoxHabitacionTipo, 0, 102, Short.MAX_VALUE))
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelNumeroPiso)
                                                    .addComponent(jLabelLimiteHuesped))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jSpinnerNumeroPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldLimiteHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCheckBox1Personaextra)
                                                    .addComponent(jCheckBox2))))))))
                        .addGap(107, 107, 107)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonMostrar)
                        .addGap(169, 169, 169))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonLimpiar, jButtonMostrar, jButtonRegistrar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCiudad)
                            .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaLlegada)
                            .addComponent(jDateChooserFechaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelFechaSalida)
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNumeroPersonas)
                                    .addComponent(jSpinnerNumeroPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNumeroPiso)
                                    .addComponent(jSpinnerNumeroPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHabitacionTipo)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxHabitacionTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelLimiteHuesped)
                                        .addComponent(jTextFieldLimiteHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelHabitacionNumero)
                                            .addComponent(jTextFieldHabitacionNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBox1Personaextra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooserFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrar))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDateChooserFechaLlegada, jDateChooserFechaSalida, jTextFieldCiudad, jTextFieldNombre});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonLimpiar, jButtonMostrar, jButtonRegistrar});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSpinnerNumeroPersona, jSpinnerNumeroPiso});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLimiteHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLimiteHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLimiteHuespedActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
//                String nomhuesped,nomciudad,/*fechallegada, fechasalida, */ tipohab ,numerohab,limhuesped;
//                int numpiso, numhuesped; 
//                  SimpleDateFormat dFormat = new SimpleDateFormat ("dd-MM-yyyy");
//                  String date = dFormat.format(jDateChooserFechaLlegada.getDate());
//                 /* SimpleDateFormat dFormat = new SimpleDateFormat ("dd-MM-yyyy");
//                  String date = dFormat.format(jDateChooserFechaSalida.getDate());*/
//                nomhuesped = this.jTextFieldNombre.getText().trim();
//                nomciudad = this.jTextFieldCiudad.getText(); 
//                tipohab = (String) this.jComboBoxHabitacionTipo.getSelectedItem(); 
//                numerohab = this.jTextFieldHabitacionNumero.getText();
//                limhuesped = this.jTextFieldLimiteHuesped.getText();
//                numpiso = (int) this.jSpinnerNumeroPiso.getValue();
//                numhuesped = (int) this.jSpinnerNumeroPiso.getValue();
        String nombre, ciudad, tipoHabitacion;
        int numHabitacion, numPersonas, numPiso;
        
        if(this.jTextFieldNombre.getText().isEmpty() || this.jTextFieldCiudad.getText().isEmpty() || this.jTextFieldHabitacionNumero.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Porfavor rellene los campos vacios");
        }
        else
        {
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            //instanseo de variables
            nombre = this.jTextFieldNombre.getText().trim();
            ciudad = this.jTextFieldCiudad.getText().trim();
            tipoHabitacion = (String) this.jComboBoxHabitacionTipo.getSelectedItem();//getSelectedIndex();
            numHabitacion = Integer.parseInt(this.jTextFieldHabitacionNumero.getText());
            numPersonas = (int) this.jSpinnerNumeroPersona.getValue();
            numPiso = (int) this.jSpinnerNumeroPiso.getValue();
            
            
            
            try
            {
                String query = "insert into registro (num_habitacion, nombre, ciudad, fecha_llegada, fecha_salida, tipo_habitacion, num_personas, num_piso) VALUES ("
                        + "'" + numHabitacion + "','" + nombre + "','" + ciudad + "','" + formato.format(this.jDateChooserFechaLlegada.getDate())
                        + "','" + formato.format(this.jDateChooserFechaSalida.getDate()) + "','" + tipoHabitacion + "','" + numPersonas + "','" + numPiso + "')";
                this.conn.Update(query);
                JOptionPane.showMessageDialog(this, "Informacion subida");//(true, "Informacion subida");
            }catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Error al subir archivos");
                System.out.println(ex);
            }
            
        }
        
        
        //numPersonas = this.jSpinnerNumeroPersona
        
        
        
//        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
//        //String fecha = dFormat.format(this.jDateChooser1.getDate());
//        
//        String query = "Insert into pruebafechasjrgp (id, nombre, fecha, totaldias) VALUES ("
//                + "'" + id + "','" + nombre + "','" + dFormat.format(this.jDateChooser1.getDate()) + "','" + t_dias + "')";

           /*   jTextFieldCiudad;
                jTextFieldHabitacionNumero;
                jTextFieldLimiteHuesped;
                jTextFieldNombre;*/
//        String query = "Insert into pacientes (nomhuesped, nomciudad, numerohab, limhuesped) VALUES ("
//                + "'" + nomhuesped + "','" + nomciudad + "','" + numerohab + /*"','" +tipohab "','" +*/ limhuesped + "')";
//                int j = this.conn.Update(query);        
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jTextFieldHabitacionNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHabitacionNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHabitacionNumeroActionPerformed

    private void jTextFieldCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCiudadActionPerformed

    private void jCheckBox1PersonaextraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1PersonaextraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1PersonaextraActionPerformed

    private void jSpinnerNumeroPersonaAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSpinnerNumeroPersonaAncestorMoved
        // TODO add your handling code here:
//        int aux = (int) jSpinnerNumeroPersona.getValue();
//        if(aux == 1)
//        {
//            
//        }
    }//GEN-LAST:event_jSpinnerNumeroPersonaAncestorMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JCheckBox jCheckBox1Personaextra;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBoxHabitacionTipo;
    private com.toedter.calendar.JDateChooser jDateChooserFechaLlegada;
    private com.toedter.calendar.JDateChooser jDateChooserFechaSalida;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelFechaLlegada;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelHabitacionNumero;
    private javax.swing.JLabel jLabelHabitacionTipo;
    private javax.swing.JLabel jLabelLimiteHuesped;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroPersonas;
    private javax.swing.JLabel jLabelNumeroPiso;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerNumeroPersona;
    private javax.swing.JSpinner jSpinnerNumeroPiso;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldHabitacionNumero;
    private javax.swing.JTextField jTextFieldLimiteHuesped;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
