/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

import controlMySQL.MySqlConn;

/**
 *
 * @author rajop
 */
public class Registro4 extends javax.swing.JPanel {

    
    MySqlConn conn = new MySqlConn();
    
    public Registro4(MySqlConn conn)
    {
        this.conn = conn;
        initComponents();
    }
    
    /**
     * Creates new form Registro4
     */
    public Registro4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonHab1 = new javax.swing.JButton();
        jButtonHab2 = new javax.swing.JButton();
        jButtonHab3 = new javax.swing.JButton();
        jButtonHab4 = new javax.swing.JButton();
        jButtonHab5 = new javax.swing.JButton();
        jButtonHab10 = new javax.swing.JButton();
        jButtonHab9 = new javax.swing.JButton();
        jButtonHab8 = new javax.swing.JButton();
        jButtonHab7 = new javax.swing.JButton();
        jButtonHab6 = new javax.swing.JButton();
        jButtonHab11 = new javax.swing.JButton();
        jButtonHab12 = new javax.swing.JButton();
        jButtonHab13 = new javax.swing.JButton();
        jButtonHab14 = new javax.swing.JButton();
        jButtonHab15 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonHab16 = new javax.swing.JButton();
        jButtonHab17 = new javax.swing.JButton();
        jButtonHab18 = new javax.swing.JButton();
        jButtonHab19 = new javax.swing.JButton();
        jButtonHab20 = new javax.swing.JButton();
        jButtonHab21 = new javax.swing.JButton();
        jButtonHab22 = new javax.swing.JButton();
        jButtonHab23 = new javax.swing.JButton();
        jButtonHab24 = new javax.swing.JButton();
        jButtonHab25 = new javax.swing.JButton();
        jButtonHab26 = new javax.swing.JButton();
        jButtonHab27 = new javax.swing.JButton();
        jButtonHab28 = new javax.swing.JButton();
        jButtonHab29 = new javax.swing.JButton();
        jButtonHab30 = new javax.swing.JButton();

        jButtonHab1.setText("001");
        jButtonHab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab1ActionPerformed(evt);
            }
        });

        jButtonHab2.setText("002");

        jButtonHab3.setText("003");

        jButtonHab4.setText("004");

        jButtonHab5.setText("005");

        jButtonHab10.setText("010");

        jButtonHab9.setText("009");

        jButtonHab8.setText("008");

        jButtonHab7.setText("007");

        jButtonHab6.setText("006");

        jButtonHab11.setText("011");

        jButtonHab12.setText("012");

        jButtonHab13.setText("013");

        jButtonHab14.setText("014");

        jButtonHab15.setText("015");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonHab11)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHab12)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHab13)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHab14)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHab15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonHab6)
                            .addComponent(jButtonHab1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonHab2)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab3)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab4)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonHab7)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab8)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab9)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab10)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHab1)
                    .addComponent(jButtonHab2)
                    .addComponent(jButtonHab3)
                    .addComponent(jButtonHab4)
                    .addComponent(jButtonHab5))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHab6)
                    .addComponent(jButtonHab7)
                    .addComponent(jButtonHab8)
                    .addComponent(jButtonHab9)
                    .addComponent(jButtonHab10))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHab11)
                    .addComponent(jButtonHab12)
                    .addComponent(jButtonHab13)
                    .addComponent(jButtonHab14)
                    .addComponent(jButtonHab15))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PISO 1", jPanel1);

        jButtonHab16.setText("016");
        jButtonHab16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab16ActionPerformed(evt);
            }
        });

        jButtonHab17.setText("017");

        jButtonHab18.setText("018");

        jButtonHab19.setText("19");

        jButtonHab20.setText("020");

        jButtonHab21.setText("021");

        jButtonHab22.setText("022");

        jButtonHab23.setText("023");

        jButtonHab24.setText("24");

        jButtonHab25.setText("025");

        jButtonHab26.setText("026");

        jButtonHab27.setText("027");

        jButtonHab28.setText("028");

        jButtonHab29.setText("029");

        jButtonHab30.setText("030");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonHab26)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHab27)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHab28)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHab29)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHab30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonHab21)
                            .addComponent(jButtonHab16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonHab17)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab18)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab19)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonHab22)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab23)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab24)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab25)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHab16)
                    .addComponent(jButtonHab17)
                    .addComponent(jButtonHab18)
                    .addComponent(jButtonHab19)
                    .addComponent(jButtonHab20))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHab21)
                    .addComponent(jButtonHab22)
                    .addComponent(jButtonHab23)
                    .addComponent(jButtonHab24)
                    .addComponent(jButtonHab25))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHab26)
                    .addComponent(jButtonHab27)
                    .addComponent(jButtonHab28)
                    .addComponent(jButtonHab29)
                    .addComponent(jButtonHab30))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PISO2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHab16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab16ActionPerformed

    private void jButtonHab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab1ActionPerformed
        // TODO add your handling code here:
        registro2 x = new registro2(conn, "1");
        x.setVisible(true);
    }//GEN-LAST:event_jButtonHab1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHab1;
    private javax.swing.JButton jButtonHab10;
    private javax.swing.JButton jButtonHab11;
    private javax.swing.JButton jButtonHab12;
    private javax.swing.JButton jButtonHab13;
    private javax.swing.JButton jButtonHab14;
    private javax.swing.JButton jButtonHab15;
    private javax.swing.JButton jButtonHab16;
    private javax.swing.JButton jButtonHab17;
    private javax.swing.JButton jButtonHab18;
    private javax.swing.JButton jButtonHab19;
    private javax.swing.JButton jButtonHab2;
    private javax.swing.JButton jButtonHab20;
    private javax.swing.JButton jButtonHab21;
    private javax.swing.JButton jButtonHab22;
    private javax.swing.JButton jButtonHab23;
    private javax.swing.JButton jButtonHab24;
    private javax.swing.JButton jButtonHab25;
    private javax.swing.JButton jButtonHab26;
    private javax.swing.JButton jButtonHab27;
    private javax.swing.JButton jButtonHab28;
    private javax.swing.JButton jButtonHab29;
    private javax.swing.JButton jButtonHab3;
    private javax.swing.JButton jButtonHab30;
    private javax.swing.JButton jButtonHab4;
    private javax.swing.JButton jButtonHab5;
    private javax.swing.JButton jButtonHab6;
    private javax.swing.JButton jButtonHab7;
    private javax.swing.JButton jButtonHab8;
    private javax.swing.JButton jButtonHab9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
